spring:
  application:
    name: greeting-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"    
